AllCops:
  Exclude:
    - 'vendor/**/*'
  RunRailsCops: true
  DisplayCopNames: true

Style/AccessModifierIndentation:
  Enabled: false

Style/AccessorMethodName:
  Enabled: false

Style/Alias:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/ArrayJoin:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/AsciiIdentifiers:
  Enabled: false

Style/Attr:
  Enabled: false

Style/BeginBlock:
  Enabled: false

Style/BarePercentLiterals:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/BlockEndNewline:
  Enabled: false

Style/Blocks:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Style/ClassAndModuleCamelCase:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassCheck:
  Enabled: false

Style/ClassMethods:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/ColonMethodCall:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/CommentIndentation:
  Enabled: false

Style/ConstantName:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/DeprecatedHashMethods:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DotPosition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/EmptyLineBetweenDefs:
  Enabled: false

Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundAccessModifier:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/EmptyLiteral:
  Enabled: false

Style/EndBlock:
  Enabled: false

Style/EndOfLine:
  Enabled: false

Style/EvenOdd:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FirstParameterIndentation:
  Enabled: false

Style/FlipFlop:
  Enabled: false

Style/For:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/IfWithSemicolon:
  Enabled: false

Style/IndentationConsistency:
  Enabled: false

Style/IndentationWidth:
  Enabled: false

Style/IndentArray:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/InfiniteLoop:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/LeadingCommentSpace:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: false

Style/MethodCallParentheses:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/MethodName:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MultilineBlockLayout:
  Enabled: false

Style/MultilineIfThen:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/MultilineTernaryOperator:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false

Style/Next:
  Enabled: false

Style/NilComparison:
  Enabled: false

Style/NonNilCheck:
  Enabled: false

Style/Not:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/OneLineConditional:
  Enabled: false

Style/OpMethod:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/PercentQLiterals:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/PredicateName:
  Enabled: false

Style/Proc:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RedundantException:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/SelfAssignment:
  Enabled: false

Style/Semicolon:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAfterColon:
  Enabled: false

Style/SpaceAfterComma:
  Enabled: false

Style/SpaceAfterControlKeyword:
  Enabled: false

Style/SpaceAfterMethodName:
  Enabled: false

Style/SpaceAfterNot:
  Enabled: false

Style/SpaceAfterSemicolon:
  Enabled: false

Style/SpaceBeforeBlockBraces:
  Enabled: false

Style/SpaceBeforeComma:
  Enabled: false

Style/SpaceBeforeComment:
  Enabled: false

Style/SpaceBeforeSemicolon:
  Enabled: false

Style/SpaceInsideBlockBraces:
  Enabled: false

Style/SpaceAroundBlockParameters:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceBeforeModifierKeyword:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/SpaceInsideParens:
  Enabled: false

Style/SpaceInsideRangeLiteral:
  Enabled: false

Style/SpecialGlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/StructInheritance:
  Enabled: false

Style/SymbolLiteral:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/Tab:
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/TrailingComma:
  Enabled: false

Style/TrailingWhitespace:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/UnlessElse:
  Enabled: false

Style/UnneededCapitalW:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false

Style/UnneededPercentX:
  Enabled: false

Style/VariableInterpolation:
  Enabled: false

Style/VariableName:
  Enabled: false

Style/WhenThen:
  Enabled: false

Style/WhileUntilDo:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/AmbiguousOperator:
  Enabled: true

Lint/AmbiguousRegexpLiteral:
  Enabled: true

Lint/AssignmentInCondition:
  Enabled: true

Lint/BlockAlignment:
  Enabled: true

Lint/ConditionPosition:
  Enabled: true

Lint/Debugger:
  Enabled: true

Lint/DefEndAlignment:
  Enabled: true

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/ElseLayout:
  Enabled: true

Lint/EmptyEnsure:
  Enabled: true

Lint/EmptyInterpolation:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/EndInMethod:
  Enabled: true

Lint/EnsureReturn:
  Enabled: true

Lint/Eval:
  Enabled: true

Lint/HandleExceptions:
  Enabled: true

Lint/InvalidCharacterLiteral:
  Enabled: true

Lint/LiteralInCondition:
  Enabled: true

Lint/LiteralInInterpolation:
  Enabled: true

Lint/Loop:
  Enabled: true

Lint/ParenthesesAsGroupedExpression:
  Enabled: true

Lint/RequireParentheses:
  Enabled: true

Lint/RescueException:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/SpaceBeforeFirstArg:
  Enabled: true

Lint/StringConversionInInterpolation:
  Enabled: true

Lint/UnderscorePrefixedVariableName:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true

Lint/UnreachableCode:
  Enabled: true

Lint/UselessAccessModifier:
  Enabled: true

Lint/UselessAssignment:
  Enabled: true

Lint/UselessComparison:
  Enabled: true

Lint/UselessElseWithoutRescue:
  Enabled: true

Lint/UselessSetterCall:
  Enabled: true

Lint/Void:
  Enabled: true

Performance/Detect:
  Enabled: true

Performance/ReverseEach:
  Enabled: true

Rails/ActionFilter:
  Enabled: true

Rails/Date:
  Enabled: true

Rails/DefaultScope:
  Enabled: true

Rails/Delegate:
  Enabled: true

Rails/HasAndBelongsToMany:
  Enabled: true

Rails/Output:
  Enabled: true

Rails/ReadWriteAttribute:
  Enabled: true

Rails/ScopeArgs:
  Enabled: true

Rails/TimeZone:
  Enabled: true

Rails/Validation:
  Enabled: true
